Dydx:
  Network:
    host: https://api.stage.dydx.exchange
    chainID: 5
  User:
    limitFee: 0.2
Perpetual:
  Network:
    host: https://goerli.optimism.io/
  User:
    slippage: 0.05
ApolloX:
  Network:
    host: https://fapi.apollox.finance
  User:
    slippage: 0.05
